### ISSUE TITLE
Thumb size

### ISSUE THREAD

**Issue by javiersamaniego** [syedowaisali/crystal-range-seekbar#23]
Hi! Is there a way for changing the thumb size? I want it more small but layout_height dont work :/

Ty

**Comment by ryust** [comment]
I would also like a better way to set the thumb size programmatically without having to alter the dimens.xml file. Since you can change other attributes of thumbs programmatically it would seem wise to add the ability to do the same with thumb sizes. I have a need to dynamically change the thumb size at runtime. The default size is way too big compared to Google's Material Design guidelines.

**Comment by bgenchel** [comment]
in addition to this, i'm seeing the thumb image getting clipped because of it's size; there is no instruction in your guide for how to fix that.

**Comment by sp0rk** [comment]
This issue is still to be resolved. Please consider fixing it.

**Comment by ghost** [comment]
Can you please stop closing the issues without answering whether this feature exists or not
